package model;
// Generated 31/07/2012 21:45:50 by Hibernate Tools 3.2.1.GA



/**
 * Carro generated by hbm2java
 */
public class Carro  implements java.io.Serializable {


     private Integer id;
     private String marca;
     private Integer ano;
     private String modelo;
     private String foto;
     private Integer dono;
     private Integer votos;
     private Integer impressao;

    public Carro() {
    }

    public Carro(String marca, Integer ano, String modelo, String foto, Integer dono, Integer votos, Integer impressao) {
       this.marca = marca;
       this.ano = ano;
       this.modelo = modelo;
       this.foto = foto;
       this.dono = dono;
       this.votos = votos;
       this.impressao = impressao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Integer getDono() {
        return this.dono;
    }
    
    public void setDono(Integer dono) {
        this.dono = dono;
    }
    public Integer getVotos() {
        return this.votos;
    }
    
    public void setVotos(Integer votos) {
        this.votos = votos;
    }
    public Integer getImpressao() {
        return this.impressao;
    }
    
    public void setImpressao(Integer impressao) {
        this.impressao = impressao;
    }




}


