package model;
// Generated 31/07/2012 21:45:50 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer idMarca;
     private String nome;
     private Set modelos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(String nome) {
        this.nome = nome;
    }
    public Marca(String nome, Set modelos) {
       this.nome = nome;
       this.modelos = modelos;
    }
   
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set modelos) {
        this.modelos = modelos;
    }




}


