package model;
// Generated 31/07/2012 21:45:50 by Hibernate Tools 3.2.1.GA



/**
 * Modelo generated by hbm2java
 */
public class Modelo  implements java.io.Serializable {


     private Integer idModelo;
     private Marca marca;
     private int nome;

    public Modelo() {
    }

    public Modelo(Marca marca, int nome) {
       this.marca = marca;
       this.nome = nome;
    }
   
    public Integer getIdModelo() {
        return this.idModelo;
    }
    
    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public int getNome() {
        return this.nome;
    }
    
    public void setNome(int nome) {
        this.nome = nome;
    }




}


